@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

interface Action << interface >> {
  + execute(int): void
  + clone(): Action
}
class AdminUser {
  - serialVersionUID: long
  + getRole(): String
  + canManageHouse(House): boolean
  + isAdmin(): boolean
}
class ApertureDevice {
  - openingPercentage: int
  + clone(): ApertureDevice
  + getStatus(): String
  + getOpeningPercentage(): int
  + open(int): void
  + setOpeningPercentage(int, int): void
  + close(int): void
}
class Automation {
  - condition: Condition
  - actions: List<Action>
  - active: boolean
  - serialVersionUID: long
  - name: String
  + addAction(Action): void
  + getName(): String
  + setActive(boolean): void
  + hashCode(): int
  + deactivate(): void
  + evaluate(int): void
  + clone(): Automation
  + activate(): void
  + equals(Object): boolean
  + isActive(): boolean
  + getCondition(): Condition
  + getActions(): List<Action>
  + toString(): String
}
class AutomationUI {
  - menu: Menu
  + showMenu(): int
  + displayAutomations(List<Automation>): void
  + displaySchedules(List<Schedule>): void
  + showError(String): void
  + readDeviceId(): String
  + showSuccess(String): void
  + readAutomationData(): String[]
  + readScheduleData(): String[]
}
class Blinds {
  + clone(): Blinds
}
interface ColorAdjustable << interface >> {
  + getColorTemperature(): int
  + setColorTemperature(int): void
  + hasColorSupport(): boolean
}
interface Condition << interface >> {
  + isMet(): boolean
  + getDescription(): String
}
class ControllerAutomations {
  - model: DomusController
  - automationUI: AutomationUI
  - createSchedule(): void
  + handle(): void
  - listSchedules(): void
  - createAutomation(): void
  - listAutomations(): void
  - evaluateAutomations(): void
}
class ControllerDevices {
  - deviceUI: DeviceUI
  - model: DomusController
  - main: ControllerTotal
  - viewDeviceStatus(): void
  - turnOffDevice(): void
  - createDevice(): void
  - controlDeviceAttributes(): void
  - turnOnDevice(): void
  + handleGuest(): void
  - listDevicesOfUser(): void
  - addDeviceToRoom(): void
  + handle(): void
  - listDevices(): void
}
class ControllerHouses {
  - model: DomusController
  - houseUI: HouseUI
  - main: ControllerTotal
  + viewHousesOnly(): void
  - createHouse(): void
  - addRoom(): void
  - listHouses(): void
  - viewHouseDetails(): void
  - addGuestToHouse(): void
  + handle(): void
}
class ControllerScenarios {
  - model: DomusController
  - scenarioUI: ScenarioUI
  - main: ControllerTotal
  - createScenario(): void
  - listScenarios(): void
  + handle(): void
  - executeScenario(): void
  - addActionToScenario(): void
}
class ControllerStatistics {
  - model: DomusController
  - statisticsUI: StatisticsUI
  - main: ControllerTotal
  + handle(): void
}
class ControllerTime {
  - model: DomusController
  - timeUI: TimeUI
  + handle(): void
}
class ControllerTotal {
  - ctrlUsers: ControllerUsers
  - ctrlDevices: ControllerDevices
  - loggedUser: User
  - ctrlHouses: ControllerHouses
  - ctrlTime: ControllerTime
  - controller: DomusController
  - ctrlStatistics: ControllerStatistics
  - ctrlScenarios: ControllerScenarios
  - mainUI: MainUI
  - ctrlAutomations: ControllerAutomations
  - handleLogin(): void
  - isAdmin(): boolean
  - handleRegister(): void
  - handleDashboard(): void
  + currentTotalMinutes(): int
  + run(): void
  + getLoggedUser(): User
}
class ControllerUsers {
  - model: DomusController
  - userUI: UserUI
  - createUser(): void
  + promoteUserRegister(String): void
  + handle(): void
  - viewUserDetails(): void
  - promoteUser(): void
  - listUsers(): void
}
class Device {
  - totalOnTime: int
  - powerPerHour: double
  - on: boolean
  - timeOnStart: int
  - serialVersionUID: long
  - id: String
  - model: String
  - activationCount: int
  - brand: String
  + setModel(String): void
  + clone(): Device
  + turnOn(int): void
  + toString(): String
  + getId(): String
  + getActivationCount(): int
  + getPowerPerHour(): double
  + equals(Object): boolean
  + setBrand(String): void
  + turnOff(int): void
  + getEffectiveTotalOnTime(int): int
  + isOn(): boolean
  + getStatus(): String
  + getBrand(): String
  + getModel(): String
  + getTotalOnTime(): int
  + setPowerPerHour(double): void
  + hashCode(): int
}
class DeviceUI {
  - controlMenu: Menu
  - guestMenu: Menu
  - menu: Menu
  + showMenu(): int
  + readVolume(): int
  + showSuccess(String): void
  + readBrightness(): int
  + displayDevice(Device): void
  + readDeviceId(): String
  + showError(String): void
  + showControlMenu(): int
  + readAddToRoomData(): String[]
  + showGuestMenu(): int
  + readColorTemperature(): int
  + readDeviceData(): String[]
  + readOpeningPercentage(): int
  + displayDevices(List<Device>): void
}
interface Dimmable << interface >> {
  + getBrightness(): int
  + setBrightness(int): void
}
class DomusController {
  - houses: List<House>
  - users: List<User>
  - scenarios: List<Scenario>
  - devices: List<Device>
  - schedules: List<Schedule>
  - serialVersionUID: long
  - automations: List<Automation>
  - time: TimeSimulator
  + addUser(User): void
  + getHouseById(String): House
  + getHighestConsumingHouse(): House
  + getAllDevices(): List<Device>
  + getTopDevicesByTime(int, int): List<Device>
  + getTopDevicesByActivationsByHouse(House, int, int): List<Device>
  + getTime(): TimeSimulator
  + getTotalSystemConsumption(): double
  + addDevice(Device): void
  + getHouses(): List<House>
  + removeDevice(String): boolean
  + getTopDevicesByActivations(int): List<Device>
  + getTopRoomsByDeviceCount(int): List<String>
  + evaluateSchedules(): void
  + getUserWithMostHouses(): User
  + addAutomation(Automation): void
  + getUserById(String): User
  + getDeviceById(String): Device
  + addScenario(Scenario): void
  + getUsers(): List<User>
  + promoteToAdmin(String): void
  + getTopDevicesByTimeByHouse(House, int, int): List<Device>
  + evaluateAutomations(): void
  + addHouse(House): void
  + getScenarios(): List<Scenario>
  + getAutomations(): List<Automation>
  + addSchedule(Schedule): void
  + removeUser(String): boolean
  + getSchedules(): List<Schedule>
  + executeScenario(String, int): void
  + tick(): void
  + removeHouse(String): boolean
}
class GarageDoor {
  + clone(): GarageDoor
}
interface HasVolume << interface >> {
  + getVolume(): int
  + setVolume(int): void
}
class House {
  - name: String
  - admins: List<User>
  - serialVersionUID: long
  - users: List<User>
  - address: String
  - rooms: List<Room>
  - id: String
  + setName(String): void
  + setAddress(String): void
  + getTotalPowerConsumption(): double
  + getName(): String
  + getRoomByName(String): Room
  + getRoomCount(): int
  + removeAdmin(User): boolean
  + isAdmin(User): boolean
  + addUser(User): void
  + removeUser(User): boolean
  + getId(): String
  + addRoom(Room): void
  + getAdmins(): List<User>
  + equals(Object): boolean
  + removeRoom(String): boolean
  + addAdmin(User): void
  + getAllDevices(): List<Device>
  + hashCode(): int
  + getRooms(): List<Room>
  + getUsers(): List<User>
  + getAddress(): String
  + toString(): String
}
class HouseUI {
  - menu: Menu
  + showMenu(): int
  + showSuccess(String): void
  + readRoomData(): String[]
  + readHouseId(): String
  + showError(String): void
  + readHouseData(): String[]
  + displayHouseDetails(House): void
  + displayHouses(List<House>): void
  + readGuestData(): String[]
}
class LightSensor {
  + clone(): LightSensor
}
class Main {
  + main(String[]): void
}
class MainUI {
  - menu: Menu
  + showMenu(): int
  + readLoginData(): String[]
  + askPromoteToAdmin(): boolean
  + showError(String): void
  + showGoodbye(): void
  + showSuccess(String): void
  + showDashboard(String, boolean): int
  + readRegisterData(): String[]
}
class Menu {
  - title: String
  - options: String[]
  - scanner: Scanner
  + readInt(String): int
  + readDouble(String): double
  + readLine(String): String
  + showMessage(String): void
  + show(): int
}
class RainSensor {
  + clone(): RainSensor
}
class RegularUser {
  - serialVersionUID: long
  + canManageHouse(House): boolean
  + getRole(): String
  + isAdmin(): boolean
}
class Relay {
  + getStatus(): String
  + clone(): Relay
}
class Room {
  - id: String
  - name: String
  - serialVersionUID: long
  - devices: List<Device>
  + getDevices(): List<Device>
  + getDeviceCount(): int
  + getDeviceById(String): Device
  + hashCode(): int
  + getId(): String
  + setName(String): void
  + equals(Object): boolean
  + getName(): String
  + removeDevice(String): boolean
  + toString(): String
  + addDevice(Device): void
}
class Scenario {
  - owner: User
  - name: String
  - serialVersionUID: long
  - actions: List<Action>
  + execute(int): void
  + clone(): Scenario
  + getOwner(): User
  + equals(Object): boolean
  + addAction(Action): void
  + getName(): String
  + getActions(): List<Action>
  + hashCode(): int
  + toString(): String
}
class ScenarioUI {
  - menu: Menu
  - actionMenu: Menu
  + readScenarioName(): String
  + readActionData(): String[]
  + showSuccess(String): void
  + showError(String): void
  + showActionMenu(): int
  + displayScenarios(List<Scenario>): void
  + showMenu(): int
  + readScenarioData(): String[]
}
class Schedule {
  - minute: int
  - name: String
  - repeating: boolean
  - active: boolean
  - serialVersionUID: long
  - hour: int
  - actions: List<Action>
  + setActive(boolean): void
  + getName(): String
  + evaluate(int, int, int): void
  + deactivate(): void
  + isRepeating(): boolean
  + getActions(): List<Action>
  + addAction(Action): void
  + clone(): Schedule
  + getHour(): int
  + isActive(): boolean
  + getMinute(): int
  + toString(): String
  + activate(): void
}
class Sensor {
  - unit: String
  - currentValue: double
  # validateValue(double): void
  + setValue(double): void
  + getValue(): double
  + getUnit(): String
  + getStatus(): String
  + clone(): Sensor
}
class SensorCondition {
  - threshold: double
  - serialVersionUID: long
  - sensor: Sensor
  - operator: Operator
  + getDescription(): String
  + isMet(): boolean
}
class SetBrightnessAction {
  - serialVersionUID: long
  - brightness: int
  - light: Dimmable
  + clone(): SetBrightnessAction
  + execute(int): void
  + toString(): String
}
class SetOpeningAction {
  - serialVersionUID: long
  - device: ApertureDevice
  - percentage: int
  + execute(int): void
  + clone(): SetOpeningAction
  + toString(): String
}
class SetVolumeAction {
  - serialVersionUID: long
  - speaker: SmartSpeaker
  - volume: int
  + execute(int): void
  + toString(): String
  + clone(): SetVolumeAction
}
class SmartLight {
  - colorTemperature: int
  - brightness: int
  - colorSupport: boolean
  + getStatus(): String
  + setBrightness(int): void
  + getBrightness(): int
  + getColorTemperature(): int
  + hasColorSupport(): boolean
  + setColorTemperature(int): void
  + clone(): SmartLight
}
class SmartSpeaker {
  - volume: int
  + getVolume(): int
  + clone(): SmartSpeaker
  + getStatus(): String
  + setVolume(int): void
}
class StateManager {
  - FILE_NAME: String
  + save(DomusController): void
  + load(): DomusController?
}
class StatisticsUI {
  - menu: Menu
  + displayTopDevicesByActivationsByHouse(House, List<Device>): void
  + displayTopDevicesByTimeByHouse(House, List<Device>, int): void
  + displayUserWithMostHouses(User): void
  + displayHighestConsumingHouse(House): void
  + displayTotalSystemConsumption(double): void
  + displayTopDevicesByTime(List<Device>, int): void
  + displayTopRooms(List<String>): void
  + showMenu(): int
  + showError(String): void
  + readHouseId(): String
  + displayTopDevicesByActivations(List<Device>): void
}
class TemperatureSensor {
  + clone(): TemperatureSensor
}
class TimeSimulator {
  - serialVersionUID: long
  - hour: int
  - minute: int
  - day: int
  + getDay(): int
  + advance(int): void
  + toString(): String
  + getHour(): int
  + tick(): void
  + getMinute(): int
}
class TimeUI {
  - menu: Menu
  + showMenu(): int
  + displayTime(String): void
  + showSuccess(String): void
  + readMinutes(): int
}
class TurnOffAction {
  - serialVersionUID: long
  - device: Device
  + clone(): TurnOffAction
  + execute(int): void
  + toString(): String
}
class TurnOnAction {
  - serialVersionUID: long
  - device: Device
  + toString(): String
  + clone(): TurnOnAction
  + execute(int): void
}
class User {
  - serialVersionUID: long
  - name: String
  - password: String
  - email: String
  - id: String
  - guestHouses: List<House>
  - ownedHouses: List<House>
  + getOwnedHouses(): List<House>
  + isAdminOf(House): boolean
  + setPassword(String): void
  + setEmail(String): void
  + addOwnedHouse(House): void
  + checkPassword(String): boolean
  + setGuestHouses(List<House>): void
  + canManageHouse(House): boolean
  + isAdmin(): boolean
  + hasAccessTo(House): boolean
  + getAllHouses(): List<House>
  + equals(Object): boolean
  + getEmail(): String
  + setName(String): void
  + addGuestHouse(House): void
  + getName(): String
  + hashCode(): int
  + toString(): String
  + getId(): String
  + getGuestHouses(): List<House>
  + setOwnedHouses(List<House>): void
  + promoteToAdminUser(): AdminUser
  + getRole(): String
  # getPassword(): String
}
class UserUI {
  - menu: Menu
  + readUserId(): String
  + readUserData(): String[]
  + displayUsers(List<User>): void
  + displayUser(User): void
  + showError(String): void
  + showMenu(): int
  + showSuccess(String): void
}

AdminUser              -[#000082,plain]-^  User                  
ApertureDevice         -[#000082,plain]-^  Device                
Automation            "1" *-[#595959,plain]-> "actions\n*" Action                
Automation            "1" *-[#595959,plain]-> "condition\n1" Condition             
AutomationUI          "1" *-[#595959,plain]-> "menu\n1" Menu                  
AutomationUI           -[#595959,dashed]->  Menu                  : "«create»"
Blinds                 -[#000082,plain]-^  ApertureDevice        
ControllerAutomations  -[#595959,dashed]->  Automation            : "«create»"
ControllerAutomations "1" *-[#595959,plain]-> "automationUI\n1" AutomationUI          
ControllerAutomations "1" *-[#595959,plain]-> "model\n1" DomusController       
ControllerAutomations  -[#595959,dashed]->  Schedule              : "«create»"
ControllerAutomations  -[#595959,dashed]->  SensorCondition       : "«create»"
ControllerAutomations  -[#595959,dashed]->  TurnOnAction          : "«create»"
ControllerDevices      -[#595959,dashed]->  Blinds                : "«create»"
ControllerDevices     "1" *-[#595959,plain]-> "main\n1" ControllerTotal       
ControllerDevices     "1" *-[#595959,plain]-> "deviceUI\n1" DeviceUI              
ControllerDevices     "1" *-[#595959,plain]-> "model\n1" DomusController       
ControllerDevices      -[#595959,dashed]->  GarageDoor            : "«create»"
ControllerDevices      -[#595959,dashed]->  LightSensor           : "«create»"
ControllerDevices      -[#595959,dashed]->  RainSensor            : "«create»"
ControllerDevices      -[#595959,dashed]->  Relay                 : "«create»"
ControllerDevices      -[#595959,dashed]->  SmartLight            : "«create»"
ControllerDevices      -[#595959,dashed]->  SmartSpeaker          : "«create»"
ControllerDevices      -[#595959,dashed]->  TemperatureSensor     : "«create»"
ControllerHouses      "1" *-[#595959,plain]-> "main\n1" ControllerTotal       
ControllerHouses      "1" *-[#595959,plain]-> "model\n1" DomusController       
ControllerHouses       -[#595959,dashed]->  House                 : "«create»"
ControllerHouses      "1" *-[#595959,plain]-> "houseUI\n1" HouseUI               
ControllerHouses       -[#595959,dashed]->  Room                  : "«create»"
ControllerScenarios   "1" *-[#595959,plain]-> "main\n1" ControllerTotal       
ControllerScenarios   "1" *-[#595959,plain]-> "model\n1" DomusController       
ControllerScenarios    -[#595959,dashed]->  Scenario              : "«create»"
ControllerScenarios   "1" *-[#595959,plain]-> "scenarioUI\n1" ScenarioUI            
ControllerScenarios    -[#595959,dashed]->  SetBrightnessAction   : "«create»"
ControllerScenarios    -[#595959,dashed]->  SetOpeningAction      : "«create»"
ControllerScenarios    -[#595959,dashed]->  SetVolumeAction       : "«create»"
ControllerScenarios    -[#595959,dashed]->  TurnOffAction         : "«create»"
ControllerScenarios    -[#595959,dashed]->  TurnOnAction          : "«create»"
ControllerStatistics  "1" *-[#595959,plain]-> "main\n1" ControllerTotal       
ControllerStatistics  "1" *-[#595959,plain]-> "model\n1" DomusController       
ControllerStatistics  "1" *-[#595959,plain]-> "statisticsUI\n1" StatisticsUI          
ControllerTime        "1" *-[#595959,plain]-> "model\n1" DomusController       
ControllerTime        "1" *-[#595959,plain]-> "timeUI\n1" TimeUI                
ControllerTotal        -[#595959,dashed]->  AutomationUI          : "«create»"
ControllerTotal        -[#595959,dashed]->  ControllerAutomations : "«create»"
ControllerTotal       "1" *-[#595959,plain]-> "ctrlAutomations\n1" ControllerAutomations 
ControllerTotal       "1" *-[#595959,plain]-> "ctrlDevices\n1" ControllerDevices     
ControllerTotal        -[#595959,dashed]->  ControllerDevices     : "«create»"
ControllerTotal        -[#595959,dashed]->  ControllerHouses      : "«create»"
ControllerTotal       "1" *-[#595959,plain]-> "ctrlHouses\n1" ControllerHouses      
ControllerTotal        -[#595959,dashed]->  ControllerScenarios   : "«create»"
ControllerTotal       "1" *-[#595959,plain]-> "ctrlScenarios\n1" ControllerScenarios   
ControllerTotal       "1" *-[#595959,plain]-> "ctrlStatistics\n1" ControllerStatistics  
ControllerTotal        -[#595959,dashed]->  ControllerStatistics  : "«create»"
ControllerTotal        -[#595959,dashed]->  ControllerTime        : "«create»"
ControllerTotal       "1" *-[#595959,plain]-> "ctrlTime\n1" ControllerTime        
ControllerTotal        -[#595959,dashed]->  ControllerUsers       : "«create»"
ControllerTotal       "1" *-[#595959,plain]-> "ctrlUsers\n1" ControllerUsers       
ControllerTotal        -[#595959,dashed]->  DeviceUI              : "«create»"
ControllerTotal        -[#595959,dashed]->  DomusController       : "«create»"
ControllerTotal       "1" *-[#595959,plain]-> "controller\n1" DomusController       
ControllerTotal        -[#595959,dashed]->  HouseUI               : "«create»"
ControllerTotal        -[#595959,dashed]->  MainUI                : "«create»"
ControllerTotal       "1" *-[#595959,plain]-> "mainUI\n1" MainUI                
ControllerTotal        -[#595959,dashed]->  RegularUser           : "«create»"
ControllerTotal        -[#595959,dashed]->  ScenarioUI            : "«create»"
ControllerTotal        -[#595959,dashed]->  StatisticsUI          : "«create»"
ControllerTotal        -[#595959,dashed]->  TimeUI                : "«create»"
ControllerTotal       "1" *-[#595959,plain]-> "loggedUser\n1" User                  
ControllerTotal        -[#595959,dashed]->  UserUI                : "«create»"
ControllerUsers       "1" *-[#595959,plain]-> "model\n1" DomusController       
ControllerUsers        -[#595959,dashed]->  RegularUser           : "«create»"
ControllerUsers       "1" *-[#595959,plain]-> "userUI\n1" UserUI                
DeviceUI               -[#595959,dashed]->  Menu                  : "«create»"
DeviceUI              "1" *-[#595959,plain]-> "menu\n1" Menu                  
DomusController       "1" *-[#595959,plain]-> "automations\n*" Automation            
DomusController       "1" *-[#595959,plain]-> "devices\n*" Device                
DomusController       "1" *-[#595959,plain]-> "houses\n*" House                 
DomusController       "1" *-[#595959,plain]-> "scenarios\n*" Scenario              
DomusController       "1" *-[#595959,plain]-> "schedules\n*" Schedule              
DomusController       "1" *-[#595959,plain]-> "time\n1" TimeSimulator         
DomusController        -[#595959,dashed]->  TimeSimulator         : "«create»"
DomusController       "1" *-[#595959,plain]-> "users\n*" User                  
GarageDoor             -[#000082,plain]-^  ApertureDevice        
House                 "1" *-[#595959,plain]-> "rooms\n*" Room                  
House                 "1" *-[#595959,plain]-> "admins\n*" User                  
HouseUI                -[#595959,dashed]->  Menu                  : "«create»"
HouseUI               "1" *-[#595959,plain]-> "menu\n1" Menu                  
LightSensor            -[#000082,plain]-^  Sensor                
Main                   -[#595959,dashed]->  ControllerTotal       : "«create»"
MainUI                "1" *-[#595959,plain]-> "menu\n1" Menu                  
MainUI                 -[#595959,dashed]->  Menu                  : "«create»"
RainSensor             -[#000082,plain]-^  Sensor                
RegularUser            -[#000082,plain]-^  User                  
Relay                  -[#000082,plain]-^  Device                
Room                  "1" *-[#595959,plain]-> "devices\n*" Device                
Scenario              "1" *-[#595959,plain]-> "actions\n*" Action                
Scenario              "1" *-[#595959,plain]-> "owner\n1" User                  
ScenarioUI            "1" *-[#595959,plain]-> "menu\n1" Menu                  
ScenarioUI             -[#595959,dashed]->  Menu                  : "«create»"
Schedule              "1" *-[#595959,plain]-> "actions\n*" Action                
Sensor                 -[#000082,plain]-^  Device                
SensorCondition        -[#008200,dashed]-^  Condition             
SensorCondition       "1" *-[#595959,plain]-> "sensor\n1" Sensor                
SetBrightnessAction    -[#008200,dashed]-^  Action                
SetBrightnessAction   "1" *-[#595959,plain]-> "light\n1" Dimmable              
SetOpeningAction       -[#008200,dashed]-^  Action                
SetOpeningAction      "1" *-[#595959,plain]-> "device\n1" ApertureDevice        
SetVolumeAction        -[#008200,dashed]-^  Action                
SetVolumeAction       "1" *-[#595959,plain]-> "speaker\n1" SmartSpeaker          
SmartLight             -[#008200,dashed]-^  ColorAdjustable       
SmartLight             -[#000082,plain]-^  Device                
SmartLight             -[#008200,dashed]-^  Dimmable              
SmartSpeaker           -[#000082,plain]-^  Device                
SmartSpeaker           -[#008200,dashed]-^  HasVolume             
StatisticsUI          "1" *-[#595959,plain]-> "menu\n1" Menu                  
StatisticsUI           -[#595959,dashed]->  Menu                  : "«create»"
TemperatureSensor      -[#000082,plain]-^  Sensor                
TimeUI                "1" *-[#595959,plain]-> "menu\n1" Menu                  
TimeUI                 -[#595959,dashed]->  Menu                  : "«create»"
TurnOffAction          -[#008200,dashed]-^  Action                
TurnOffAction         "1" *-[#595959,plain]-> "device\n1" Device                
TurnOnAction           -[#008200,dashed]-^  Action                
TurnOnAction          "1" *-[#595959,plain]-> "device\n1" Device                
User                   -[#595959,dashed]->  AdminUser             : "«create»"
User                  "1" *-[#595959,plain]-> "ownedHouses\n*" House                 
UserUI                 -[#595959,dashed]->  Menu                  : "«create»"
UserUI                "1" *-[#595959,plain]-> "menu\n1" Menu                  
@enduml
